# Generated by Django 5.1 on 2025-01-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_payment_mode_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=500),
        ),
    ]
