# Generated by Django 5.1 on 2025-01-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_country_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
