# Generated by Django 5.1 on 2025-01-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent',
            new_name='reference',
        ),
    ]
